package com.aura.auraid.model;

public enum NotificationType {
    ACCESS_REQUEST_SUBMITTED,
    ACCESS_REQUEST_APPROVED,
    ACCESS_REQUEST_REJECTED,
    ACCESS_REQUEST_CANCELLED,
    RESOURCE_CREATED,
    RESOURCE_UPDATED,
    RESOURCE_DELETED,
    PERMISSION_GRANTED,
    PERMISSION_REVOKED
} 