package com.aura.auraid.enums;

public enum SecurityEventType {
    FAILED_LOGIN_ATTEMPT,
    MULTIPLE_FAILED_LOGINS,
    ACCOUNT_LOCKED,
    PASSWORD_RESET_REQUEST,
    SUSPICIOUS_IP_ACCESS,
    ROLE_CHANGE,
    ADMIN_ACTION,
    PERMISSION_VIOLATION
} 